version: "3.5"
x-environment:
  &QUICKSTART_ENVIRONMENT # These are read from .env file. The values in the .env file maybe overriden by shell envvars
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  PLAID_ENV: ${PLAID_ENV}
  APP_PORT: ${APP_PORT}
  FRONTEND_PORT: ${FRONTEND_PORT}
services:
  go:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./go/Dockerfile
    ports: ["${APP_PORT}:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  java:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./java/Dockerfile
    ports: ["${APP_PORT}:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  node:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./node/Dockerfile
    ports: ["${APP_PORT}:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  python:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./python/Dockerfile
    ports: ["${APP_PORT}:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  ruby:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./ruby/Dockerfile
    ports: ["${APP_PORT}:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  frontend:
    environment:
      - REACT_APP_API_HOST
      - PORT=${FRONTEND_PORT}
      - HOST=${FRONTEND_HOST}
    networks:
      - "quickstart"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports: ["${FRONTEND_PORT}:${FRONTEND_PORT}"]
networks:
  quickstart:
    name: quickstart
